<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>0d8ef90a-cd00-43ff-b855-27446dce7435</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.19.0" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.19.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.19.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.19.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.19.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CalcioAnalytic.Application\CalcioAnalytic.Application.csproj" />
    <ProjectReference Include="..\CalcioAnalytic.Infrastructure\CalcioAnalytic.Infrastructure.csproj" />
    <ProjectReference Include="..\CalcioAnalytic.Analytics\CalcioAnalytic.Analytics.csproj" />
    <ProjectReference Include="..\CalcioAnalytic.Ingestion\CalcioAnalytic.Ingestion.csproj" />
  </ItemGroup>

</Project>
